# .bashrc

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\W\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
# User specific aliases and functions

alias cp='cp -i'
alias mv='mv -i'
alias ll='ls -al'
alias sl='ls'
alias la='ls -a'
alias l='ls'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
export LD_LIBRARY_PATH=/usr/local/gdev/lib64
export PATH=$PATH:/usr/lib64/mpich-3.2/bin/:/home/XXX/.scripts/:/home/XXX/.local/bin
alias sea='grep -PRIns --exclude-dir=.git/ --exclude=tags --exclude=*cscope* --exclude=*elf --exclude=*map --exclude=*.o'
alias ff='find . -name'
alias gsd='git status'
alias gb='git branch'
alias vi='vim'
SWGCC_VERSION=650
export PATH=/home/XXX/.opt/usr/bin:/home/XXX/.opt/swgcc710-tools-AI-$SWGCC_VERSION/usr/bin:$PATH
export PATH=/usr/local/cuda-11.5/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/home/XXX/.opt/swgcc710-tools-AI-$SWGCC_VERSION/usr/lib_for_gcc/lib:${LD_LIBRARY_PATH}
export UK_KRAFT_GITHUB_TOKEN=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
